export enum FCOLL {
  "TRANSACTIONS" = "transactions",
}

export enum FIREACT {
  "IS_PENDING" = "IS_PENDING",
  "ADDED_DOCUMENT" = "ADDED_DOCUMENT",
  "ERROR" = "ERROR",
  "SOFT_DELETED_DOCUMENT" = "DELETED_DOCUMENT",
  "HARD_DELETE_DOCUMENT" = "HARD_DELETE_DOCUMENT",
  "RESTORE_DOCUMENT" = "RESTORE_DOCUMENT",
}
